# Deploy the web application
# into the deno deploy as production
#
# ***** NOTE ******
# This deployment need to setup some secrets

name: Api Production

# Only run this workflows if
# the user start manual the actions
# and push the code into the main branch
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "apps/api/**"

env:
  DENO_DEPLOY_TOKEN: ${{secrets.DENO_DEPLOY_TOKEN}}

jobs:
  deploy:
    name: Update API App
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read
      
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Setup Deno Environment
        uses: denoland/setup-deno@v1
        with:
          deno-version: 1.37.0

      - name: Cache Dependencies
        working-directory: ./apps/api
        run: deno task install

      - name: Deploy to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: cooble-api
          entrypoint: src/main.ts
          root: apps/api
        
